In [1]:
import numpy as np
import math

there are several iterative methods that you can use to approximate Ax=b

$x_n=g(x_{n-1})=x_{n-1}+M^{-1}r_{n-1}$
1. Jacobi method: M=D, diagonal of A
2. Gauss-Seidal method: M=E, the lower triangular part of A

In [2]:
x=np.array([1,0,0])#our intial guess
A=np.array([[7,3,1],
            [-3,10,2],
            [1,7,-15]
           ])
b=np.array([3,4,2])


def Jacobi(A,b,x0,iterations):
    D=np.diag(np.diag(A),0)
    M_inv=np.linalg.inv(D)
    for i in range(iterations):
        r=b-A@x0
        x0=x0+M_inv@r
        print("k=",i+1,":x=",x0)
    return x0
Jacobi(A,b,x,10)

k= 1 :x= [ 0.42857143  0.7        -0.06666667]
k= 2 :x= [0.13809524 0.54190476 0.22190476]
k= 3 :x= [0.16462585 0.39704762 0.1287619 ]
k= 4 :x= [0.24001361 0.42363537 0.06293061]
k= 5 :x= [0.23802332 0.45941796 0.08036408]
k= 6 :x= [0.22019743 0.45533418 0.09692994]
k= 7 :x= [0.21958107 0.44667324 0.09383578]
k= 8 :x= [0.22373493 0.44710717 0.08975292]
k= 9 :x= [0.22413223 0.44916989 0.09023234]
k= 10 :x= [0.22317971 0.4491932  0.09122143]


array([0.22317971, 0.4491932 , 0.09122143])

In [4]:
A@ np.array([0.21958107,0.44667324,0.09383578])

array([2.97092299, 3.99566075, 1.93875705])

In [4]:
def Gauss_seidal(A,b,x0,iterations):
    m,n=A.shape
    E=np.zeros((m,n))
    for i in range(m):
        for j in range(i+1):
            E[i][j]=A[i][j]
    M_inv=np.linalg.inv(E)
    
    for i in range(iterations):
        r=b-A@x0
        x0=x0+M_inv@r
        print("k=",i+1,":x=",x0)
    return x0
Gauss_seidal(A,b,x,10)

k= 1 :x= [1.  0.5 0.9]
k= 2 :x= [1.13333333 0.98333333 1.05      ]
k= 3 :x= [1.02222222 1.03055556 1.015     ]
k= 4 :x= [0.99481481 1.0062037  0.99916667]
k= 5 :x= [0.99765432 0.99899691 0.99886111]
k= 6 :x= [0.99995473 0.99941924 0.99986574]
k= 7 :x= [1.00014883 0.99997008 1.00005355]
k= 8 :x= [1.00002782 1.00003373 1.00001788]
k= 9 :x= [0.99999471 1.00000762 0.99999941]
k= 10 :x= [0.99999726 0.99999902 0.99999871]


array([0.99999726, 0.99999902, 0.99999871])