In [4]:
import numpy as np
from scipy.linalg import lu

In [2]:
#Use numpy.linalg.solve to solve the following equations.
# 4𝑥1+3𝑥2−5𝑥3=2
# −2𝑥1−4𝑥2+5𝑥3=5
# 8𝑥1+8𝑥2=−3
A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [3]:
#Under the hood, the solver is actually doing a LU decomposition to get the results. 
A_inv = np.linalg.inv(A)
x = np.dot(A_inv, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [5]:
P, L, U = lu(A)
print('P:\n', P)
print('L:\n', L)
print('U:\n', U)
print('LU:\n',np.dot(L, U))

P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U:
 [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
LU:
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]
