In [1]:
import numpy as np
from scipy.linalg import lu
from numpy.linalg import norm, det,inv
from numpy.linalg import cond,matrix_rank
import math

# Vectors 

### vector norm

1. **L2 norm**(Euclian length): $||v||_2=\sqrt{\sum_{i}^{}(v_i)^2}$
1. **L1 norm**(Manhattan norm): $||v||_1=\sum_{i}^{}|v_i|$
1. **Lp norm**: $||p||_p=\sqrt[p]{(\sum_{i}^{}(v_i)^p)}$

### dot product
* **dot product** of two vectors is the sum of the product of the respective elements in each vector and is denoted by *.
* d=$\sum_{i=1}^{n} v_i*w_i$; dot product of v and w whose dimension is n
* v*w=$||v||_2 ||w||_2 cos(\theta)$

### cross product
* $vXw=||v||_2||w||_2 sin(\theta)$, where $\theta$ is the angle between v and w(can be computed from dot product) and n is a vector perpendicular to both v and w with unit length.
* geometric interpretation of the cross product: a vector perpendicular to both v and w with length equal to the area enclosed by the parallelogram created by the two vectors.

### linearly independent
A set is called **linearly independent** if no object in the set can be written as a linear combination of the other objects in the set.

In [2]:
#row vector and column vector
vector_row=np.array([[1,-5,3,2,4]])
print(vector_row.shape)

vector_col=np.array([[1],[2],[3],[4]])
print(vector_col.shape)

(1, 5)
(4, 1)


In [3]:
# transpose and norm
new_vec=vector_row.T
print(new_vec)

n1=norm(new_vec,1)
n2=norm(new_vec,2)
ninf=norm(new_vec,np.inf)
print('L1 norm is %.2f'%n1)
print('L2 norm is %.2f'%n2)
print('Linf norm is %.2f'%ninf)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]
L1 norm is 15.00
L2 norm is 7.42
Linf norm is 5.00


In [25]:
v=np.array([[10,9,3]])
w=np.array([[2,5,12]])
theta=np.arccos(np.dot(v,w.T)/(norm(v)*norm(w)))
print(theta)

print("cross product",np.cross(v,w))

[[0.97992471]]
cross product [[  93 -114   32]]


# Matrices
### matrix norm
* $||M||_p=\sqrt[p]{\sum_{i}^{m}\sum_{j}^{n}|a_{ij}|^p}$ M is a mXn matrix
* calculate matrix norm using **norm** function in Numpy

### determinant
* determinant **det(M)** is an important property of square matrices
* identiy matrix I has ones on the diagonal and zeros elsewhere

### inverse
1. inverse of a square matrix M: M*N=I, where N=$M^{-1}$ 
1. matrices having an inverse are called **non-singular**; matrices without inverses are **singular**.
1. how to determine whether a matrix has an inverse: find its det
* if det is 0, singular; no inverse
* if det is not 0, nonsingular; has inverse

### ill-conditioned and condition number
* a **ill-conditioned** matrix is almost singular
* **condition number** is a measure of how **ill-conditioned** a matirx is. The higher the conditon number, the closer the matrix is to being singular.

### Rank
* rank(A): the number of linearly independent columns/rows in A. The number of linearly independent rows=number of linearly independent columns.
* *full rank* if rank(A)=min(m,n)

In [27]:
#find the dot product of two matrices
P=np.array([[1,7],[2,3],[5,0]])
Q=np.array([[2,6,3,1],[1,2,3,4]])
print(P)
print(Q)
print("The product of two matrices:\n",np.dot(P,Q))

[[1 7]
 [2 3]
 [5 0]]
[[2 6 3 1]
 [1 2 3 4]]
The product of two matrices:
 [[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


In [32]:
# finding the det and inverse
M=np.array([[0,2,1,3],
            [3,2,8,1],
            [1,0,0,3],
            [0,3,2,1]])
print("M:\n",M)
print("Determinant of M:\n",det(M))
print("M has an inverse b/c det is not zero")
print("Inv M:\n",inv(M))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant of M:
 -38.000000000000014
M has an inverse b/c det is not zero
Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]


In [71]:
A=np.array([[-8, 0, -1], [0, 1, 0], [1, 0, 1]])
print("det(A):",det(A))
print("condition number:",cond(A))# A is close to being singular but not singular
print("rank:",matrix_rank(A))

det(A): -6.999999999999998
condition number: 9.465784928823194
rank: 3


# Systems of Linear Equations
1. Ax=y
1. three distinct solution possibilities for x
* no sol for x
* one, unique sol for x
* inf number of sol for x
1. **LU decomposition** method to solve linear systems of linear equations
* turn A into multiple of two matrices L and U, where L is lower triangular and U is an upper triangular
2. Gaussian elimiation followed by forward substitution followed by backward substitution

In [2]:
#Use numpy.linalg.solve to solve the following equations.
# 4𝑥1+3𝑥2−5𝑥3=2
# −2𝑥1−4𝑥2+5𝑥3=5
# 8𝑥1+8𝑥2=−3
A = np.array([[4, 3, -5], 
              [-2, -4, 5], 
              [8, 8, 0]])
b = np.array([2, 5, -3])
x = np.linalg.solve(np.array([[7,4],[3,6]]), np.array([1,1]))
print(x)

[0.06666667 0.13333333]


In [3]:
#Under the hood, the solver is actually doing a LU decomposition to get the results. 
A_inv = np.linalg.inv(A)
x = np.dot(A_inv, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [62]:
from scipy.linalg import lu
P, L, U = lu(A)
print('P:\n', P)
print('L:\n', L)
print('U:\n', U)
print('LU:\n',np.dot(L, U))

P:
 [[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L:
 [[ 1.    0.    0.  ]
 [-0.25  1.    0.  ]
 [ 0.5   0.5   1.  ]]
U:
 [[ 8.   8.   0. ]
 [ 0.  -2.   5. ]
 [ 0.   0.  -7.5]]
LU:
 [[ 8.  8.  0.]
 [-2. -4.  5.]
 [ 4.  3. -5.]]


In [64]:
P@np.array([1,2,3])

array([3., 2., 1.])

# codes for 328

In [44]:
# backward substitution
U=np.array([[3,2,1],[0,2,-2],[0,0,5]])
n=len(U)
b=np.array([2,6,-10])
x=np.zeros(n)

for i in range(n-1,-1,-1):
    x[i]=b[i]
    for j in range(i+1,n):
        x[i]-=U[i,j]*x[j]
    x[i]/=U[i,i]
print(x)

[ 0.66666667  1.         -2.        ]


In [39]:
def backward_sub(U,c):
    n=len(U)
    x=np.zeros(n)
    for i in range(n-1,-1,-1):
        x[i]=c[i]
        for j in range(i+1,n):
            x[i]-=U[i,j]*x[j]
        x[i]=x[i]/U[i,i]
    return x
# backward_sub(np.array([[2,1,0],
#                       [0,1.5,1],
#                       [0,0,4/3]],dtype='float'),np.array([0,-3,0]))
        

In [66]:
def forward_sub(L,b):
    n=len(L)
    
    b[0]=b[0]/L[0,0]
    for i in range(1,n):#row values
        for j in range(i):
            b[i]=b[i]-L[i,j]*b[i-1]
        b[i]=b[i]/L[i,i]
    return b#our c
forward_sub(np.array([[6,3,4],
                     [0,-0.5,0],[0,0,3]],dtype='float'),np.array([1,0,3]))

# def lu_solve(A,b):
#     P,L,U=lu(A)
#     b=P@b
#     c=forward_sub(L,b)
#     x=backward_sub(U,c)
#     return c
# lu_solve(np.array([[3,1,2],[6,3,4],[3,1,5]],dtype='float'),np.array([0,1,3]))
    

array([0, 0, 1])

In [2]:
#LU decomposition
A=np.array([[1,2,1],
            [3,8,1],
           [0,4,1]])
n=len(A)
L=np.identity(n)
for j in range(n-1):
    for i in range(j+1,n):
        L[i,j]=A[j+1,j]/A[j,j] #multiplier=L[i,j]
        A[i,:]=A[i,:]-L[i,j]*A[j,:]#subtract multiplier
print(A)
print(L)

[[ 1  2  1]
 [ 0  2 -2]
 [ 0  0  5]]
[[1. 0. 0.]
 [3. 1. 0.]
 [0. 2. 1.]]


In [52]:
def LU_dec(A):#The elements of A has dtype of float
    m,n=A.shape
    if m!=n:
        print("A is not a square; LU only applies to square matrix")
        return
    elif np.linalg.det(A)==0:
        print("A is singular; LU only applied to non-singulat matrix")
        return
    else:
        L=np.identity(n)
        for j in range(n-1):#loop each column from j=0 to j=n-2
              for i in range(j+1,n):#loop rows
                  L[i,j]=(A[j+1,j]/A[j,j])#multiplier
                  A[i,:]=A[i,:]-L[i,j]*A[j,:]
        return L,A#return L,A
LU_dec(np.array([[2,-3],
                [5,6]],dtype="float"))



# def lu(A):
    
#     #Get the number of rows
#     n = A.shape[0]
    
#     U = A.copy()
#     L = np.eye(n, dtype=np.double)
    
#     #Loop over rows
#     for i in range(n):
            
#         #Eliminate entries below i with row operations 
#         #on U and reverse the row operations to 
#         #manipulate L
#         factor = U[i+1:, i] / U[i, i]
#         L[i+1:, i] = factor
#         U[i+1:] -= factor[:, np.newaxis] * U[i]
        
#     return L@U

# lu(np.array([[2,-3],
#              [5,6]],dtype='float'))
              

(array([[1. , 0. ],
        [2.5, 1. ]]),
 array([[ 2. , -3. ],
        [ 0. , 13.5]]))

In [2]:
A=np.array([[1,1],[1,1.0001]])
B=np.array([[0.0001,1],[1,1]])
print("condition number for A:",cond(A))
print("condition number for B:",cond(B))

condition number for A: 40002.00007491187
condition number for B: 2.6183852736548263


In [3]:
cond(np.array([[1,2],[1.0001,2]]))

50001.0000298737

In [8]:
math.sqrt(6+4*math.sqrt(2))

3.414213562373095