In [14]:
import numpy as np
import math

In [36]:
#find eigenvalues and eigenvectors using linalg.eig

a,b=np.linalg.eig(np.array([[-1,2,2],[-1,-4,-2],[-3,9,7]]))
print("eigenvalues:",a)
print("eigenvectors:",b)

eigenvalues: [ 3.  1. -2.]
eigenvectors: [[ 3.01511345e-01  4.08248290e-01 -5.96744876e-16]
 [-3.01511345e-01 -4.08248290e-01 -7.07106781e-01]
 [ 9.04534034e-01  8.16496581e-01  7.07106781e-01]]


## power method
the **power method** is based on repeated multiplication of the n by n square matrix A on a random vector $x_0$ (almost any intial vector will do). The resulting FPI is $x_{k+1}=g(x_k)=Ax_k$ gravitates towards the direction of the dominant eigenvector

In [37]:
#A is the matrix: n by n square matrix
#v is our initla guess
#n: number of iterations
# look for dominant eigenvector
A=np.array([[-1,2,2],
            [-1,-4,-2],
            [-3,9,7]])
v=np.array([1,0,0])
def power_method(A,v,n):
    for i in range(n):
        v=A@v
        v=v/np.linalg.norm(v)
        lam=np.dot(v, A@v)
        print(i+1,v,lam)
power_method(A,v,20)

1 [-0.30151134 -0.30151134 -0.90453403] 7.000000000000001
2 [-0.23346307  0.36687054 -0.90050042] 2.4749721913236926
3 [-0.33186166  0.22566593 -0.91593817] 3.7330396475770904
4 [-0.27880057  0.33526651 -0.89992589] 2.685344559166033
5 [-0.31590132  0.27395592 -0.90838016] 3.260586140124501
6 [-0.29189446  0.31759081 -0.90218274] 2.8471580642243968
7 [-0.30796797  0.28992683 -0.90614467] 3.1092513208091415
8 [-0.29725666  0.30885869 -0.90346266] 2.930110504422389
9 [-0.30437715  0.29645879 -0.90524402] 3.047726703216416
10 [-0.29961691  0.3048129  -0.90405686] 2.968642581827357
11 [-0.30278232  0.29928181 -0.90484986] 3.02109187541328
12 [-0.30066792  0.30298528 -0.90432225] 2.9860166247940434
13 [-0.30207546  0.30052332 -0.90467461] 3.0093549801095723
14 [-0.30113612  0.30216766 -0.90444002] 2.993777296700909
15 [-0.30176188  0.30107276 -0.90459657] 3.004154463876502
16 [-0.30134449  0.30180327 -0.90449228] 2.9972329547166483
17 [-0.30162266  0.30131652 -0.90456184] 3.0018458286144427

In [38]:
np.linalg.solve(np.array([[-1,2,2],
            [-1,-4,-2],
            [-3,9,7]]), np.array([1,0,0]))

array([ 1.66666667, -2.16666667,  3.5       ])

In [18]:
#look for minimum eigenvector 
def power_var(A,v,n):
    for i in range(n):
        v=np.linalg.solve(A,v)
        v=v/np.linalg.norm(v)
        lam=np.dot(v,A@v)
        print(i+1,v,lam)
power_var(A,v,20)

1 [0.4472136  0.89442719] 9.0
2 [-0.17888544  0.98386991] 4.800000000000001
3 [-0.55930131  0.82896444] 3.0673316708229423
4 [-0.66559985  0.74630881] 2.965821936508725
5 [-0.69494857  0.71905944] 2.9849881897641666
6 [-0.70348661  0.71070851] 2.9950759559356985
7 [-0.70602321  0.7081887 ] 2.9984851814325237
8 [-0.70678193  0.70743148] 2.999542176658195
9 [-0.70700935  0.7072042 ] 2.9998623491810754
10 [-0.70707755  0.70713601] 2.9999586774158065
11 [-0.70709801  0.70711555] 2.999987600764409
12 [-0.70710415  0.70710941] 2.9999962800078954
13 [-0.70710599  0.70710757] 2.9999988839824407
14 [-0.70710654  0.70710702] 2.9999996651929384
15 [-0.70710671  0.70710685] 2.9999998995577206
16 [-0.70710676  0.7071068 ] 2.999999969867301
17 [-0.70710677  0.70710679] 2.9999999909601893
18 [-0.70710678  0.70710678] 2.999999997288056
19 [-0.70710678  0.70710678] 2.9999999991864175
20 [-0.70710678  0.70710678] 2.999999999755926


In [20]:
#alpha is your eigenvalue approximate
def power_var2(A,v,n,alpha):
    for i in range(n):
        v=np.linalg.solve(A-alpha*np.eye(len(A)),v)
        v=v/np.linalg.norm(v)
        lam=np.dot(v,A@v)
        print(i+1,v,lam)
power_var2(A,v,20,8)


1 [0.83205029 0.5547002 ] 9.92307692307692
2 [0.78631834 0.61782155] 10.018927444794953
3 [0.80533688 0.59281743] 9.990491680220192
4 [0.79784337 0.60286479] 10.003495783462332
5 [0.80085916 0.59885274] 9.998552315943403
6 [0.79965578 0.60045869] 10.000571184580982
7 [0.8001376  0.59981649] 9.999770263258725
8 [0.79994495 0.6000734 ] 10.000091692673339
9 [0.80002202 0.59997064] 9.99996329060425
10 [0.79999119 0.60001174] 10.000014678586247
11 [0.80000352 0.5999953 ] 9.999994127737962
12 [0.79999859 0.60000188] 10.000002348772409
13 [0.80000056 0.59999925] 9.999999060469847
14 [0.79999977 0.6000003 ] 10.000000375808671
15 [0.80000009 0.59999988] 9.99999984967599
16 [0.79999996 0.60000005] 10.000000060129516
17 [0.80000001 0.59999998] 9.999999975948176
18 [0.79999999 0.60000001] 10.000000009620726
19 [0.8 0.6] 9.999999996151711
20 [0.8 0.6] 10.000000001539314


## SVD factorization
$A=U \Sigma V^T$ where $U$ and $V^T$ are orthogonal matrices and $\Sigma$ is diagonal

1. find the eigenvalues $\lambda_i$ and unit eigenvectors $v_i$ of $A^TA$
2. let columns of the matrix V be the unit eigenvectors of $v_i$
3. let $u_1=\frac{Av_1}{||Av_1||}$, $u_2=\frac{Av_2}{||Av_2||}$,...,$u_n=\frac{Av_n}{||Av_n||}$ be columns of the matrix U
4. the diagonal matrix have diagonal elements the singular values $\sigma_1=\sqrt{\lambda_1}$,$\sigma_2=\sqrt{\lambda_2}$,...,$\sigma_m=\sqrt{\lambda_m}$

In [35]:
u, s, vh = np.linalg.svd(np.array([[6,2],[-7,6]]), full_matrices=True)
print(u)
print(s)
print(vh)

[[-0.4472136   0.89442719]
 [ 0.89442719  0.4472136 ]]
[10.  5.]
[[-0.89442719  0.4472136 ]
 [ 0.4472136   0.89442719]]


In [22]:
np.array([[6,2],[-7,6]]).T @ np.array([[6,2],[-7,6]])

array([[ 85, -30],
       [-30,  40]])

In [42]:
# def svd_manual(A):
#     w,v=np.linalg.eig(A.T@A)
#     v_normalized=[]
#     for i in v:
#         v_normalized.append(i/np.linalg.norm(i))
#     v_normalized=np.array(v_normalized).T
    
#     sig=np.eye(len(A))
#     for i in range(len(A)):
#         sig[i][i]=math.sqrt(w[i])
    
    
#     w2,u=np.linalg.eig(A@A.T)
# #     for i in v_normalized:
# #         u.append((A@i)/np.linalg.norm(A@i))
#     print("U:",u)
#     print("Sigma:",sig)
#     print("V.T:",v_normalized)
#     print(u@sig@v_normalized)
# svd_manual(np.array([[6,2],[-7,6]]))