In [21]:
import numpy as np
from numpy.linalg import norm
from numpy.linalg import det
from numpy.linalg import inv
from numpy.linalg import cond, matrix_rank

In [4]:
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row.shape)
print(vector_column.shape)

(1, 5)
(4, 1)


# norm
1. L1 (Manhattan distance): $||$v$||_1$=|$v_1$|+|$v_2$|+...+|$v_n$|

2. L2: Euclidian distance

3. LP

In [6]:
new_vector = vector_row.T
print(new_vector)

[[ 1]
 [-5]
 [ 3]
 [ 2]
 [ 4]]


In [7]:
norm_1 = norm(new_vector, 1)#1+5+3+2+4=15
norm_2 = norm(new_vector, 2)#(1+25+9+4+16)^(1/2)=(55)^(1/2)
norm_inf = norm(new_vector, np.inf)
print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)
print('L_inf is: %.1f'%norm_inf)

L_1 is: 15.0
L_2 is: 7.4
L_inf is: 5.0


# vector algebra
1. Vector addition is defined as the pairwise addition of each of the elements of the added vectors.
2. Vector multiplication can be defined in several ways depending on the context. Scalar multiplication of a vector is the product of a vector and a scalar. 
3. The dot product of two vectors is the sum of the product of the respective elements in each vector and is denoted by ⋅, and 𝑣⋅𝑤 is read “v dot w.” 

The angle between two vectors, 𝜃, is defined by the formula: $𝑣⋅𝑤=‖𝑣‖_2‖𝑤‖_2cos𝜃$

4. cross product between two vectors, 𝑣 and 𝑤, is written 𝑣×𝑤. It is defined by $𝑣×𝑤=‖𝑣‖_2‖𝑤‖_2sin(𝜃)n$, where 𝜃 is the angle between the 𝑣 and 𝑤 (which can be computed from the dot product) and 𝑛 is a vector perpendicular to both 𝑣 and 𝑤 with unit length (i.e., the length is one).
5. A set is called linearly independent if no object in the set can be written as a linear combination of the other objects in the set. For the purposes of this book, we will only consider the linear independence of a set of vectors. A set of vectors that is not linearly independent is linearly dependent.

In [11]:
#Compute the angle between the vectors 𝑣=[10,9,3] and 𝑤=[2,5,12].
v = np.array([[10, 9, 3]])
w = np.array([[2, 5, 12]])

print("angle between vectors:",np.arccos(np.dot(v,w.T)/(norm(v,2)*(norm(w,2)))))

angle between vectors: [[0.97992471]]


In [13]:
#cross product: Given the vectors 𝑣=[0,2,0] and 𝑤=[3,0,0], compute its cross product
print("cross product of vectors:",np.cross(np.array([0,2,0]),np.array([3,0,0])))


cross product of vectors: [ 0  0 -6]


# matrices
An 𝑚×𝑛 matrix is a rectangular table of numbers consisting of 𝑚 rows and 𝑛 columns.
1. matrix multiplication between two matrices, 𝑃 and 𝑄, is defined when 𝑃 is an 𝑚×𝑝 matrix and 𝑄 is a 𝑝×𝑛 matrix. The result of 𝑀=𝑃𝑄 is a matrix 𝑀 that is 𝑚×𝑛.
2. A square matrix is an 𝑛×𝑛 matrix; that is, it has the same number of rows as columns. The determinant is an important property of square matrices. The determinant is denoted by 𝑑𝑒𝑡(𝑀), both in mathematics and in Numpy’s linalg package, sometimes it is also denoted as |𝑀|.
3. The identity matrix is a square matrix with ones on the diagonal and zeros elsewhere. The identity matrix is usually denoted by 𝐼, and is analagous to the real number identity, 1. That is, multiplying any matrix by 𝐼 (of compatible size) will produce the same matrix.
4. The inverse of a square matrix 𝑀 is a matrix of the same size, 𝑁, such that 𝑀⋅𝑁=𝐼. A matrix is said to be invertible if it has an inverse. The inverse of a matrix is unique; that is, for an invertible matrix, there is only one inverse for that matrix.

0 has no inverse for multiplication in the real-numbers setting. Similarly, there are matrices that do not have inverses. These matrices are called singular. Matrices that do have an inverse are called nonsingular. One way to determine if a matrix is singular is by computing its determinant. If the determinant is 0, then the matrix is singular; if not, the matrix is nonsingular.

A matrix that is close to being singular (i.e., the determinant is close to 0) is called ill-conditioned. The condition number is a measure of how ill-conditioned a matrix is, and it can be computed using Numpy’s function cond from linalg. The higher the condition number, the closer the matrix is to being singular.
 
5. The rank. of an 𝑚×𝑛 matrix 𝐴 is the number of linearly independent columns or rows of 𝐴, and is denoted by rank(𝐴).

In [15]:
#matrix multiplication using np.dot()
P = np.array([[1, 7], [2, 3], [5, 0]])#shape(3,2)
Q = np.array([[2, 6, 3, 1], [1, 2, 3, 4]])#shape(2,4)
# print(P)
# print(Q)
print(np.dot(P, Q))#shape(3,4)

[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


In [17]:
M = np.array([[0,2,1,3], 
             [3,2,8,1], 
             [1,0,0,3],
             [0,3,2,1]])
print('M:\n', M)

print('Determinant: %.1f'%det(M))
I = np.eye(4)
print('I:\n', I)
print('M*I:\n', np.dot(M, I))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.0
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


In [20]:
#Compute the inverse of 𝑀.
print('Inv M:\n', inv(M))
print("det of M:\n",det(M))

Inv M:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]
det of M:
 -38.000000000000014


In [22]:
A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])

print('Condition number:\n', cond(A))
print('Rank:\n', matrix_rank(A))
y = np.array([[1], [2], [1]])
A_y = np.concatenate((A, y), axis = 1)
print('Augmented matrix:\n', A_y)

Condition number:
 4.048917339522305
Rank:
 3
Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]
